#!/bin/sh
# backuPXE - Copyright (C) 2006-2019 Luc Deschenaux
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# this script is run from /etc/rc.d/rc.S

# you can put specific workstation configuration scripts in etc/<macaddress>/rc.d/rc.S
if [ -x etc/$HWADDR/rc.d/rc.S ] ; then
  . etc/$HWADDR/rc.d/rc.S
done

# to disable this you can quit etc/$HWADDR/rc.d/rc.S with 'return'
if grep -q captivefs /proc/cmdline ; then
  cd ./captive-static-1.1.5
  ./install
fi
