#!/bin/sh
mkdir /dev/.initramfs

[ -f /etc/usplash.conf ] && . /etc/usplash.conf

SPLASH=false
VERBOSE=true

for x in $(cat /proc/cmdline); do
	case $x in
	splash*)
		SPLASH=true
		;;
    quiet*)
        VERBOSE=false
        ;;
	esac
done

if [ $SPLASH = "true" ]; then
        mknod -m 640 /dev/mem c 1 1
	mknod -m 666 /dev/zero c 1 5
        for i in 0 1 2 3 4 5 6 7 8; do
                [ -c /dev/tty$i ] || mknod /dev/tty$i c 4 $i
	done
	modprobe -q i8042
	modprobe -q atkbd
	sleep 1
fi

/etc/rc.d/usplash-pulse &
