#!/bin/sh
# backuPXE - Copyright (C) 2006-2019 Luc Deschenaux, all rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


if [ "$1" = "--master" ] ; then
  master=" master"
  shift 1
fi

currentpass="$1"
newpass="$2"

if [ -z "$newpass" ] ; then
  echo "usage: pxepasswd [ --master ] <current_password> <new_password>"
  echo
  exit 1
fi

cd /tftpboot/pxelinux/pxelinux.cfg/
for f in `ls -1 *` ; do
   sed -r -e 's/menu'$master' passwd +'$currentpass' *$/menu passwd '$newpass/ $f > $f.new || exit 1
done
