#!/bin/sh


PATH=/usr/lib/setup:$PATH
verbose=0
mkdir -p $ROOT/tmp || exit 1
LOG=$ROOT/tmp/install.log
export LOG

wgetit () {

  gauge=0
  if [ "$1" = "--gauge" ] ; then
    gauge=1
    percent=$2
    shift 2
  fi

  fn=`echo $@ | sed -r -n -e 's/.*:\/\/[^\/]+\/(.*)/\1/p'`
  while true ; do

    if [ $gauge -eq 0 ] ; then 
      dialog --backtitle "Downloading..." --infobox "$fn" 7 100
    else
      echo XXX >> $ROOT/tmp/progress.$$.tmp
      echo $fn >> $ROOT/tmp/progress.$$.tmp
      echo XXX >> $ROOT/tmp/progress.$$.tmp
    fi

    echo > $ROOT/tmp/wget.$$.tmp || exit 1
    echo "wget $@" >> $LOG
    wget $@ 1>> $ROOT/tmp/wget.$$.tmp 2>> $ROOT/tmp/wget.$$.tmp

    if [ $? -eq 0 ] ; then
       rm $ROOT/tmp/wget.$$.tmp
       return 0 
    else
      cat $ROOT/tmp/wget.$$.tmp >> $LOG
      dialog --backtitle "Error while getting $fn" --extra-button --ok-label Retry --extra-label Skip --yesno "`tail $ROOT/tmp/wget.$$.tmp`" 0 0
      case $? in
        3)
# skip
          return 1 ;;
        1)
          exit 1 ;;
        0)
          continue ;;
        default)
          exit 1 ;;
      esac

    fi

  done

}


doinstallpkg () {

  if [ "$1" = "--gauge" ] ; then
    gauge=1
    shift 2
  else
    gauge=0
  fi

  pkg="$1"
  subdir="$2"
  url="$3"

  [ -z "$url" ] && exit 1 

  mkdir -p $WORKDIR/$subdir || exit 1
  cd $WORKDIR/$subdir || exit 1

  base=`basename "$url" .tgz`
  pkgbasename=`echo $base | sed -r -n -e 's/([^\/]+)-[^\-]+\-[^\-]+\-[^\-]+$/\1/p'`

  while true ; do

    if [ ! -f $ROOT/var/log/packages/$base ] ; then

      if [ $gauge -eq 1 ] ; then
         wgetit --gauge 0 -c $url || break 

      else
        wgetit -c $url || break 
    
        if [ ! -f $WORKDIR/$subdir/$base.txt ] ; then
          package_info $pkgbasename $base $subdir 
        fi

#        dialog --backtitle "Installing $base" --infobox "`sed -r -n -e 's/^[^ :]+: //p' $ROOT/tmp/$SOURCE/$subdir/$base.txt`" 11 -1 

      fi

      installpkg -root $ROOT $base.tgz >> $LOG || exit 1

    else
      dialog --infobox "Already installed: $pkg" 6 70  
      echo  "Already installed: $pkg" >> $LOG  

    fi
    break

  done

}

package_info () {

  pkgbasename=$1
  pkgname=$2
  subdir=$3

  cd $WORKDIR/$subdir || doexit 1

  if grep $1: $WORKDIR/PACKAGES.TXT > $ROOT/tmp/pkginfo.$$.tmp ; then
    mv $ROOT/tmp/pkginfo.$$.tmp $pkgname.txt
    return 0
  fi

  if grep -q $subdir/$pkgname.txt $WORKDIR/FILELIST.TXT ; then
    wgetit --gauge 0 $MIRROR/$subdir/$pkgname.txt || echo $pkgname > $pkgname.txt
  else
    echo $pkgname > $pkgname.txt
  fi

}


searchninstall () {

  count=0
  checklist=

  sed -r -n -e 's=.* (.*'$pkg'.*)=\1=' -e T -e '/source/b' -e p  $WORKDIR/TGZLIST.TXT > $ROOT/tmp/pkglist.$$.tmp
  pkglist=`cat $ROOT/tmp/pkglist.$$.tmp`
  pkgcount=`wc -l $ROOT/tmp/pkglist.$$.tmp | cut -d \  -f 1`
  echo > $ROOT/tmp/progress.$$.tmp
  dialog_displayed=0

  for match in `cat $ROOT/tmp/pkglist.$$.tmp` ; do
  #for match in `sed -r -n -e 's=.* \.\/((.*\/.*)?'$pkg'.*)=\1=p' $WORKDIR/TGZLIST.TXT` ; do

    match=`echo $match | sed -n -e 's/^\.\///p'`
    [ -z "$match" ] && continue  

    count=`expr $count + 1`
    url=$MIRROR/$match
    subdir=`dirname $match`
    pkgname=`basename $match .tgz`
    pkgbasename=`echo $pkgname | sed -r -n -e 's/([^\/]+)-[^\-]+\-[^\-]+\-[^\-]+$/\1/p'`
    comment=

    mkdir -p $ROOT/tmp/$SOURCE/$subdir
    cd $ROOT/tmp/$SOURCE/$subdir || exit 1

    if [ $dialog_displayed -eq 0 ] ; then
      tail -s 0 --pid $$ -f $ROOT/tmp/progress.$$.tmp | dialog --backtitle "Gathering package info" --gauge $pkgname 6 80  &
      sleep 1
      dialog_displayed=1
    fi


    echo XXX >> $ROOT/tmp/progress.$$.tmp
    echo $pkgname >> $ROOT/tmp/progress.$$.tmp
    echo XXX >> $ROOT/tmp/progress.$$.tmp

    if [ ! -f "$pkgname.txt" ] ; then
      package_info $pkgbasename $pkgname $subdir 
    fi

    comment=`sed -r -n -e "s/^[^:]+: [^\ ]+ \((.*)\)/\1/p" -e 'T l01' -e q -e ': l01' -e "s/^[^:]+: $pkgbasename\$//" -e t -e "s/^[^:]+: //p" -e T -e q $pkgname.txt | sed -n -e ': l01' -e 's/[\(\)]/-/' -e 't l01' -e p | tr \' \"` || comment= 
  
    checklist="$checklist $match '$comment' off"
  
    percent=`expr $count \* 100 / $pkgcount` 
    echo $percent >> $ROOT/tmp/progress.$$.tmp

  done
  
  if [ $pkgcount -gt 0 ] ; then 
    kill `jobs -p tail`  1> /dev/null 2> /dev/null
    sleep 1
  fi

  if [ $count -eq 0 ] ; then
    return 
  fi

  if  [ $count -gt 1 -o "$pkgbasename" != "$pkg" ] ; then 
    s= ; [ $count -gt 1 ] && s=s
    eval "dialog --separate-output  --backtitle '$count package$s' --checklist 'Select package$s to install:' 0 0 0 $checklist 2> $ROOT/tmp/pkgsel.$$.tmp"
    if [ $? -ne 0 ] ; then
       return 
    fi

    pkgcount=`wc -l $ROOT/tmp/pkgsel.$$.tmp | cut -d \  -f 1`
 
    echo > $ROOT/tmp/progress.$$.tmp
    tail -s 0 --pid $$ -f $ROOT/tmp/progress.$$.tmp | dialog --backtitle "Installing packages" --gauge "" 6 80  &
    sleep 1

    count=0;
    
    for pkgpath in `cat $ROOT/tmp/pkgsel.$$.tmp` ; do
      echo pkgpath:$pkgpath >&2
      url=$MIRROR/$pkgpath
      pkg=`basename $pkgpath .tgz`
      subdir=`dirname $pkgpath`

      echo XXX >> $ROOT/tmp/progress.$$.tmp
      echo $pkg >> $ROOT/tmp/progress.$$.tmp
      echo XXX >> $ROOT/tmp/progress.$$.tmp

      doinstallpkg --gauge 1 $pkg $subdir $url 

      count=`expr $count + 1`
      percent=`expr $count \* 100 / $pkgcount`
      echo $percent  >> $ROOT/tmp/progress.$$.tmp

    done  
  
    kill `jobs -p tail`  1> /dev/null 2> /dev/null

    exit
  
  fi
  
  doinstallpkg $pkg $subdir $url

}

pkg="$1"
if [ -z "$pkg" ] ; then
  echo "usage: netinstallpkg <regexp> [ <regexp> ]"
  exit 1
fi

if [ -z "$SOURCE" ] ; then
  export SOURCE=slackware
fi

if [ ! -f $ROOT/etc/$SOURCE-mirror ] ; then
   mkdir -p $ROOT/etc || exit 1
   choosemirror || exit 1
fi
MIRROR=`cat $ROOT/etc/$SOURCE-mirror`
[ -z "$ROOT" ] && ROOT=/
export ROOT

export WORKDIR=$ROOT/tmp/$SOURCE

if killall -0 gpm 2> /dev/null ; then
  gpm -k 2> /dev/null
fi

mkdir -p $WORKDIR || exit 1
cd $WORKDIR || exit 1

echo "--------------------------`date`" >> $LOG
[ $verbose -ne 0 ] && tail -f --pid=$$ -n 1 $LOG &

# downloading FILELIST.TXT 

if [ ! -f FILELIST.TXT ] ; then
  wgetit $MIRROR/FILELIST.TXT || exit 1
fi
grep \.tgz\$ FILELIST.TXT > TGZLIST.TXT

if [ ! -f PACKAGES.TXT ] ; then
  wgetit $MIRROR/PACKAGES.TXT || exit 1
fi

count=0
while [ -n "$pkg" ] ; do
  searchninstall $pkg 
  count=`expr $count + 1`
  shift || break
  pkg="$1"
done

if [ $count -gt 0 ] ; then
  ldconfig -r $ROOT
fi

rm $ROOT/tmp/*.$$.tmp 2> /dev/null
